apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: ar251/dashboard:backend.v3
        ports:
        - name: web-backend
          containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: backend-app
  labels:
    app: backend-app
spec:
  selector:
    app: backend-app
  ports:
  - name: web-backend
    port: 8081
    targetPort: web-backend
    
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-app
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend-app
  endpoints:
  - port: web-backend