apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: ar251/dashboard:frontend
        ports:
        - name: web
          containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: frontend-app
  labels:
    app: frontend-app
spec:
  selector:
    app: frontend-app
  ports:
  - name: web
    port: 8080
    

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-app
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend-app
  endpoints:
  - port: web