name: Backend APP - Package with Docker

on:
  push:
    branches: [ "master" ]
    paths: ['reference-app/backend/**']

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      
      
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./reference-app/backend
          file: ./reference-app/backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ar251/dashboard:backend